services:

  db:
    image: postgres
    ports:
      - "7777:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test

volumes:
  postgresql_data: